// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SGS.infra.Data;
using System;

namespace SGS.infra.Migrations
{
    [DbContext(typeof(SaudeContext))]
    [Migration("20180727123620_CriaClasserontuario")]
    partial class CriaClasserontuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGS.app.Entity.Beneficiario", b =>
                {
                    b.Property<int>("BeneficiarioID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("BeneficiarioID");

                    b.ToTable("Beneficiario");
                });

            modelBuilder.Entity("SGS.app.Entity.Prontuario", b =>
                {
                    b.Property<int>("ProntuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeneficiarioID");

                    b.Property<DateTime>("DataAtendimento");

                    b.HasKey("ProntuarioId");

                    b.HasIndex("BeneficiarioID");

                    b.ToTable("Prontuario");
                });

            modelBuilder.Entity("SGS.app.Entity.Prontuario", b =>
                {
                    b.HasOne("SGS.app.Entity.Beneficiario", "Beneficiario")
                        .WithMany("Prontuarios")
                        .HasForeignKey("BeneficiarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
